version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: t00R

  express:
    build:
      context: ./
      dockerfile: Dockerfile
    command: [ 'npm', 'start' ]
    ports:
      - '5001:3000'
    volumes:
      - ./src:/app/src:delegated
    stdin_open: true
    environment:
      VIRTUAL_HOST: back.coding-challenge.docker
      EXPRESS_PORT: 3000
      CONFIG_MONGODB_URL: mongodb://root:t00R@mongo:27017/
      CONFIG_MONGODB_NAME: DeutschePost
      MONGODB_OFFICE_COLLECTION: offices
      MONGODB_SHIPMENT_COLLECTION: shipments

networks:
  default:
    name: coding_challenge
    external: true
